name: ci

on: [ push ]

permissions:
  contents: read

env:
  NODE_VERSION: '20'

jobs:
  ci:
    name: Lint and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: ./js/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint the code
        run: yarn run lint

      - name: Check types - electron-app
        working-directory: js/electron-app
        run: yarn run check-types

      - name: Check types - react-app
        working-directory: js/react-app
        run: yarn run check-types

      - name: Build the code
        working-directory: js/electron-app
        run: yarn run build
